### ISSUE TITLE
spelling error

### ISSUE THREAD

**Issue by Baggette** [dora2-iOS/p0insettia#1]
in credits it says checkra1n team for the kernel patche methods but shouldn't it say checkra1n team for the kernel patch methods.

**Comment by Baggette** [comment]
> in credits it says checkra1n team for the kernel patche methods but shouldn't it say checkra1n team for the kernel patch methods.

ok I see it was fixed I will close this issue

**Comment by dora2-iOS** [comment]
Thanks for the spell check!
