### ISSUE TITLE
windows, iphone 5c 10.3.x support.

### ISSUE THREAD

**Issue by Baggette** [dora2-iOS/p0insettia#3]
will it support the 5c in the future and will there possibly be a windows version?(I doubt). and if it does support the 5c will it be untethered? semi-untethered? semi- tethered?

**Comment by dora2-iOS** [comment]
Future support for the iPhone 5c is possible. I am currently looking into doing that.  
There is no support for windows/linux. Some of the code used in this tool is macosx dependent.

**Comment by Baggette** [comment]
> Future support for the iPhone 5c is possible. I am currently looking into doing that. There is no support for windows/linux. Some of the code used in this tool is macosx dependent.

will this tool work on mac os mojave? (sorry Im not sure whats considered macosx)
