### ISSUE TITLE
[Not an issue with the JB] Coolbooter doesn't work

### ISSUE THREAD

**Issue by ghost** [dora2-iOS/p0insettia#4]
[CoolBooter](https://coolbooter.com/) doesn't work when the phone is jailbroken with p0insettia.
Trying to install the firmware results in CB getting stuck in the "Extracting firmware" section, while trying to boot the firmware with CB after it's installed causes the phone to simply not do that, instead the phone will be stuck at the lock screen with the home button disabled.
On the same iPhone, jailbreaking with H3lix makes both issues go away.

**Comment by dora2-iOS** [comment]
Did you insert additional entitlements in cb?

**Comment by zacchi4k** [comment]
>  Did you insert additional entitlements in cb?

Sorry, I don't understand what you mean

**Comment by ghost** [comment]
> Did you insert additional entitlements in cb?

Unfortunately I don't know how to do that

**Comment by dora2-iOS** [comment]
Please read README for this project.

**Comment by dora2-iOS** [comment]
Extract ent in xml format using ldid and insert the key indicated by readme there.  Then use that ent to re-sign with ldid.

**Comment by dora2-iOS** [comment]
If it works fine after adding that ent to cb, it's an app issue. This jailbreak applies a sandbox under '/Applications', so your app will need to add no-sandbox to ent, or run as root, to access outside the sandbox.
If you add an ent and it doesn't work, I will accept this as a known issue.

**Comment by ghost** [comment]
Yes, adding the entitlement does fix the issue (booting, uninstalling and reinstalling all work)
I'll report to the app developers. 
Thank you for your time!
